name = "cloftware-backend"  # Changed from "cloftware-contact-api"
main = "src/index.ts"
compatibility_date = "2026-07-13"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://cloftware.com,https://www.cloftware.com,http://localhost:3000,http://127.0.0.1:3000"
MAIL_FROM = "hello@cloftware.com"
MAIL_TO = "hello@cloftware.com"
SMTP_HOST = "smtp-relay.brevo.com"
SMTP_PORT = "587"